### ISSUE TITLE
The number of recon_train set objects found is 0

### ISSUE THREAD

**Issue by maurock** [facebookresearch/Active-3D-Vision-and-Touch#1]
Hi, I am having an issue when I run `object_prediction.ipynb`, `touch_chart_prediction.ipynb`, or any other notebook besides `simulator.ipynb` (which works correctly). Running the first cell in `object_prediction.ipynb`, I get this output:

```
The number of recon_train set objects found : 0
``` 
and then this error:

```
ValueError: num_samples should be a positive integer value, but got num_samples=0
```
The same happens for `touch_chart_prediction.ipynb`. I downloaded both the data and the pre-trained models using the scripts provided in the repository. 

I am running this on macOS M1, `python==3.8.13`, `torch==1.9.0 (pypi)`. 

I am not sure whether I am missing something. 

Thank you! 

Here is the traceback:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
 /Active-3D-Vision-and-Touch/notebook/Reconstruction/touch_chart_prediction.ipynb Cell 4' in <cell line: 21>()
     19 params = Params()
     20 touch_trainer = touch_train.Engine(params)
---> 21 touch_trainer()

File  ~/Active-3D-Vision-and-Touch/pterotactyl/reconstruction/touch/train.py:52, in Engine.__call__(self)
     48 self.optimizer = optim.Adam(params, lr=self.args.lr)
     49 writer = SummaryWriter(
     50     os.path.join("experiments/tensorboard/", self.args.exp_type)
     51 )
---> 52 train_loader, valid_loader = self.get_loaders()
     54 # evaluate
     55 if self.args.eval:

File  ~/Active-3D-Vision-and-Touch/pterotactyl/reconstruction/touch/train.py:77, in Engine.get_loaders(self)
     73 if not self.args.eval:
     74     train_data = data_loaders.mesh_loader_touch(
     75         self.args, set_type="recon_train"
     76     )
---> 77     train_loader = DataLoader(
     78         train_data,
     79         batch_size=self.args.batch_size,
     80         shuffle=True,
     81         num_workers=16,
     82         collate_fn=train_data.collate,
     83     )
     84 # dataloader for evaluation
     85 set_type = "test" if self.args.eval else "valid"

File ~/miniforge3/envs/active_touch/lib/python3.8/site-packages/torch/utils/data/dataloader.py:270, in DataLoader.__init__(self, dataset, batch_size, shuffle, sampler, batch_sampler, num_workers, collate_fn, pin_memory, drop_last, timeout, worker_init_fn, multiprocessing_context, generator, prefetch_factor, persistent_workers)
    266 else:  # map-style
    267     if shuffle:
    268         # Cannot statically verify that dataset is Sized
    269         # Somewhat related: see NOTE [ Lack of Default `__len__` in Python Abstract Base Classes ]
--> 270         sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
    271     else:
    272         sampler = SequentialSampler(dataset)  # type: ignore[arg-type]

File ~/miniforge3/envs/active_touch/lib/python3.8/site-packages/torch/utils/data/sampler.py:102, in RandomSampler.__init__(self, data_source, replacement, num_samples, generator)
     98     raise ValueError("With replacement=False, num_samples should not be specified, "
     99                      "since a random permute will be performed.")
    101 if not isinstance(self.num_samples, int) or self.num_samples <= 0:
--> 102     raise ValueError("num_samples should be a positive integer "
    103                      "value, but got num_samples={}".format(self.num_samples))

ValueError: num_samples should be a positive integer value, but got num_samples=0
```

**Comment by EdwardSmith1884** [comment]
Hi yes so this happens when the package cannot find your object data. When you ran the data downloader were any errors thrown and how long did it take to complete?  Also can you let me know if the folders at "pterotactyl/object_data/"  like "point_cloud_info" and "images_colourful" are filled with thousands of objects?

**Comment by maurock** [comment]
Thank you for your quick response. There were no errors when I downloaded the data. It took about 10 minutes at 15 MB/s, and `ActiveDataset.tar` was about 7 GB. All the folders in `pterodactyl/object_data/` contain thousands of files, so it looks like the data is there. Just to be sure, I re-downloaded the data and it downloaded it correctly (please check the log below), but the same thing happens when I run the notebooks.

```
HTTP request sent, awaiting response... 200 OK
Length: 7539645424 (7.0G) [application/gzip]
Saving to: ‘ActiveDataset.tar’

ActiveDataset.tar   100%[===================>]   7.02G  12.2MB/s    in 9m 54s

2022-06-21 19:12:14 (12.1 MB/s) - ‘ActiveDataset.tar’ saved [7539645424/7539645424]
```

**Comment by EdwardSmith1884** [comment]
Huh, this is strange. I downloaded everything from scratch and it is working fine on my side. The failure is happening here : https://github.com/facebookresearch/Active-3D-Vision-and-Touch/blob/0024e02a70477abe0b53ce4bf12d0668c3258bd3/pterotactyl/utility/data_loaders.py#L60 : 
<img width="465" alt="image" src="https://user-images.githubusercontent.com/26203802/174872891-d5ea1511-3a41-430b-8362-a8b998b20be1.png">
 where at every layer I am checking if the relevant data is available for that particular object. Can you maybe check  locally at which if statement it breaks? So first check if the object_data list is empty, then the if the POINT_CLOUD_LOCATION  points to a real file and then the GRASP_LOCATION? It is probably just a case of pointing to the wrong location.

**Comment by maurock** [comment]
Thank you for your help! For some mysterious reason the file `objects/data_split.npy` was empty. I downloaded it again from the repo, replaced it, and that fixed the issue.

**Comment by EdwardSmith1884** [comment]
Perfect!
